Layout/EmptyLines:
  Exclude:
    - 'Gemfile'
    - 'config/environments/development.rb'

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - 'config/environments/production.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'
    - 'db/**/*'

Style/ExpandPathArguments:
  Exclude:
    - 'bin/rails'
    - 'bin/rake'

Style/FrozenStringLiteralComment:
  Enabled: true

# Offense count: 2
Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Style/StringLiterals:
  Exclude:
    - 'bin/spring'
    - 'config/application.rb'
    - 'config/environments/production.rb'
    - 'config/puma.rb'

Style/SymbolArray:
  EnforcedStyle: brackets

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - 'db/**/*'

Metrics/AbcSize:
    Exclude:
      - 'db/**/*'

Metrics/BlockLength:
    Exclude:
      - 'db/**/*'
